# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'denizzzzp/app-fabric'

steps:

- task: Docker@2
  displayName: Docker HUB login
  inputs:
    containerRegistry: 'denizzzzp-hub'
    command: 'login'

- task: Docker@2
  displayName: Docker build
  inputs:
    containerRegistry: 'denizzzzp-hub'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)

- task: CmdLine@2
  displayName: create file docker-compose.yml
  inputs:
    script: |
      cat <<EOF >docker-compose.yml
      version: "3"
      services:
        identidock:
          image: denizzzzp/app-fabric:$(Build.BuildId)
          pull: true
          ports:
          - "80:5000"
          environment:
            ENV: DEV
      
        dnmonster:
          image: amouat/dnmonster:1.0
          ports:
          - "8080:8080"
      
        redis:
          image: redis:3.0
          ports:
          - "6379:6379"
      EOF

- task: CmdLine@2
  displayName: Print file docker-compose.yml
  inputs:
    script: 'cat docker-compose.yml'