version: "3"
services:
  identidock:
    image: denizzzzp/app-fabric:latest
    ports:
    - "80:5000"
    environment:
      ENV: DEV

  dnmonster:
    image: amouat/dnmonster:1.0

  redis:
    image: redis:3.0
