version: "3"
services:
  identidock:
    image: denizzzzp/app-fabric:$(RELEASE.ARTIFACTS..DENIZZZZP.AZDEVOPS.BUILDID)
    pull: true
    ports:
    - "80:5000"
    environment:
      ENV: DEV

  dnmonster:
    image: amouat/dnmonster:1.0
    ports:
    - "8080:8080"

  redis:
    image: redis:3.0
    ports:
    - "6379:6379"
